version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: openlibrary-postgres
    environment:
      POSTGRES_USER: ol_user
      POSTGRES_PASSWORD: ol_password
      POSTGRES_DB: openlibrary
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db_scripts:/db_scripts
      - ./data:/data
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ol_user -d openlibrary"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: "1gb"
    command: >
      postgres
      -c shared_buffers=64MB 
      -c maintenance_work_mem=32MB


volumes:
  pg_data: